## Playing with Iris Dataset
What is the Iris Dataset?
![Iris](images/03_iris.png)
* 50 samples of 3 different species of iris (150 samples total)
* Measurements: sepal length, sepal width, petal length, petal width

In [2]:
from IPython.display import HTML
HTML('<iframe src=http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data width=300 height=200></iframe>')

## Machine learning on the iris dataset
* Framed as a ***supervised learning*** problem: Predict the species of an iris using the measurements
* Famous dataset for machine learning because prediction is ***easy***
* Learn more about he iris dataset: [UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Iris)

## Loading the iris dataset into scikit-learn

In [5]:
# import load_iris function from datasets module
from sklearn.datasets import load_iris

In [6]:
# save "bunch" object containing iris dataset and its attributes
iris = load_iris()
type(iris)

sklearn.datasets.base.Bunch

In [7]:
# print the iris dataset
print iris.data

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

## Machine Learning Terminology
* Each row is an ***observation*** (aka: sample, example, instance, record)
* Each column is a ***feature*** (aka: predictor, attribute, independent variable, input, regressor, covariate)

In [9]:
# print the names of the four features
print iris.feature_names

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [10]:
# print integers representing the species of each observation
print iris.target

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [11]:
# print the encoding scheme for species 0=setosa, 1=versicolor, 2=virginica
print iris.target_names

['setosa' 'versicolor' 'virginica']


* Each value we are predicting is the ***response*** (aka: target, outcome, label, dependent variable)
* ***Classification*** is supervised learning in which the response is categorical
* ***Regression*** is supervised learning in which the response is ordered and continuous

## Requirements for working with data in scikit-learn
1. Features and responses are ***separate objects***
1. Features and response should be ***numeric ***
1. Features and response should by ***NumPy arrays***
1. Feature and response should have ***specific shapes***


In [12]:
print type(iris.data)
print type(iris.target)

<type 'numpy.ndarray'>
<type 'numpy.ndarray'>


In [14]:
# check the shape of the features (first dimension= # of observations, second dimension = # of features)
print iris.data.shape
print iris.target.shape

(150, 4)
(150,)


In [16]:
# store the feature matrix in "X"
X = iris.data

# store the response vector in "y"
y = iris.target

# Resources
* scikit-learn documentation: [Dataset loading utilities](http://scikit-learn.org/stable/datasets/)
* Jake VanderPlas: Fast Numerical Computing with NumPy ([slides](https://speakerdeck.com/jakevdp/losing-your-loops-fast-numerical-computing-with-numpy-pycon-2015), [video](https://www.youtube.com/watch?v=EEUXKG97YRw))
* Scott Shell: [An Intro to NumPy](http://www.engr.ucsb.edu/~shell/che210d/numpy.pdf)

In [17]:
from IPython.core.display import HTML
def css_styling():
    styles = open("styles/custom.css","r").read()
    return HTML(styles)
css_styling()